apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
        - name: my-web-app
          image: <345594579424>.dkr.ecr.<aws-region>.amazonaws.com/my-web-app:latest
          ports:
            - containerPort: 3000
